a = 'c'
b = 'd'
c = 'e'
d = 'f'
e = 'g'
f = 'h'
g = 'i'
h = 'j'
i = 'k'
j = 'l'
k = 'm'
l = 'n'
m = 'o'
n = 'p'
o = 'q'
p = 'r'
q = 's'
r = 't'
s = 'u'
t = 'v'
u = 'w'
v = 'x'
w = 'y'
x = 'z'
y = 'a'
z = 'b'

maketrans()
print(g+f+m+n+c+w+m+s+b+g+b+l+r+r+p+y+l+q+j+y+r+c+g+r+z+w+f+y+l+b+r+f+y+r+q+u+f+y+r+a+m+k+n+s+r+c+p+q+y+p+c+d+m+p+b+m+g+l+e+g+r+g+l+z+w+f+y+l+b+g+q+g+l+c+d+d+g+a+g+c+l+r+y+l+b+r+f+y+r+q+u+f+w+r+f+g+q+r+c+v+r+g+q+q+m+j+m+l+e+s+q+g+l+e+q+r+p+g+l+e+k+y+i+c+r+p+y+l+q + "()" + g+q+p+c+a+m+k+k+c+l+b+c+b+l+m+u+y+n+n+j+w+m+l+r+f+c+s+p+j)
